### ISSUE TITLE
Switch to sqlite db

### ISSUE THREAD

**Issue by Alien-AV** [nfusionz/CK2-DB#11]
Switching to sqlite instead of postgres would make this tool more self-contained. Having to bring up a local postgres server is a journey in itself and it doesn't help with ease-of-use.

Have you considered this?

**Comment by Darokrithia** [comment]
Thanks for looking into and contributing to this repo!  We hadn't.  The reason we used postgres is because we made this whole project for a database systems class, and in that class we were taught postgres.

How much work do you think switching would be?  What would some advantages be?  I'm happy to switch it over although we currently update this repo pretty infrequently and slowly haha

**Comment by Alien-AV** [comment]
SQLite is a file-based self-contained DB engine. It has no client-server architecture, rather it's just a library that applies SQL queries to a database stored in a local file. You wouldn't need to setup a postgres server to start using the tool.

Switching will be pretty easy, API is basically the same. I've made a test change, it seems that the only non-trivial change that would need to be done is changing parameter substitution from `%s` (postgres way) to `?` (SQLite way), which means a lot of careful find-and-replace.

Thanks for contributing to open-source in the first place :)

**Comment by Darokrithia** [comment]
That does sound more in line with the project than postgres.  I think switching is a good idea.

@OwenDurkin and I were talking and I think once we merge in your pull request we will make a new branch to switch to SQLite.

No problem!  I'm continually surprised and excited by how many people have gotten some use / entertainment out of this 😄

**Comment by Alien-AV** [comment]
Find and replace worked, (needed to fix a minor bug that was ignored by postgres library)
I don't like that the choice between the DBs will be hardcoded. I didn't find a way to dynamically choose between the parameter substitution placeholders, that is idiomatic to Python.
Still, while the change would be "final" (in a sense that it's would take the same amount of effort to change back if you decide), I agree that it would be more fitting for this project.
I can post a pull request in an hour or two with the sqlite version.

**Comment by Darokrithia** [comment]
What do you mean by
>  the choice between the DBs will be hardcoded
If you want to make the pull request that would be very helpful but we can also do it.

**Comment by Alien-AV** [comment]
> What do you mean by
> 
> > the choice between the DBs will be hardcoded

What I mean is that it would be nice to make the choice of the DB dynamic, so that you could at runtime (or with single line of code changed) select which DB you're using. OTOH, I've already reconsidered - I think if anyone would REALLY need the data in specifically postgres, they could just migrate it to postgres from the sqlite DB.

**Comment by nfusionz** [comment]
@Darokrithia Do we have any plans for keeping/updating `application.py`? We'll need to update the `psycopg` calls in that file (which is probably trivial unless we use some feature specific to postgres (possibly the recursive query)).

@Alien-AV Thanks for contributing! We could probably implement the dynamic DB by having a common interface for two DB wrapper classes, but this requires significant changes to the code and a bunch of repeated strings. I do agree that SQLite is probably better suited for this project though.

**Comment by Darokrithia** [comment]
@nfusionz Wait why would we get rid of them?  Been a while since I've really looked at the code.  I'm fine tossing them if they are obsolete, but if not then I'd think we should keep (and update) them.

**Comment by Alien-AV** [comment]
I've also edited the readme to reflect the changes, and reorganized some parts of it to better accommodate an "actual production usage" vibe as opposed to "submitting a class project"  ;)
It's in an additional pull request.

@nfusionz Glad to help. I agree that those changes are significant and aren't needed.

@Darokrithia I think that a tool to fetch certain data from the DB is useful only insofar as it allows you to do (useful) things that game itself doesn't (easily) provide. So if there is something in it a CK2 player would use, I'd keep it, otherwise, it's only nice for history reasons (as a reminder of this being a school project once). My 2 cents :)

**Comment by Darokrithia** [comment]
Thanks!  Will merge that in as well.

**Comment by Darokrithia** [comment]
Not quite done yet.  Need to fix database.py and application.py at a minimum

**Comment by OwenDurkin** [comment]
Done as of #15
