### ISSUE TITLE
Fails to load data from my game

### ISSUE THREAD

**Issue by satonio** [nfusionz/CK2-DB#8]
I tried first to load it as it is. I got that:

Preloading religion...
Preloading culture...
Preloading traits...
Reading CK2 file...
Getting dynasties...
Traceback (most recent call last):
  File "load_data.py", line 72, in <module>
    load_data(file_name)
  File "load_data.py", line 47, in load_data
    get_dynasties.get_dynasties(f, cur)
  File "/home/satonio/Descargas/CK2-DB/get_dynasties.py", line 77, in get_dynasties
    cultureID = cur.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

Then copied dynasties file from my game and got that one:

Preloading religion...
Preloading culture...
Preloading traits...
Reading CK2 file...
Getting dynasties...
Getting characters...
Traceback (most recent call last):
  File "load_data.py", line 72, in <module>
    load_data(file_name)
  File "load_data.py", line 49, in load_data
    get_chars.get_chars(f, cur)
  File "/home/satonio/Descargas/CK2-DB/get_chars.py", line 163, in get_chars
    "weak" in obj["claim"]])
psycopg2.ProgrammingError: can't adapt type 'dict'

And now i don't know what to do. I attach the savegame.

[Noregr785_08_17_prueba_herencia2.ck2.zip](https://github.com/nfusionz/CK2-DB/files/4134152/Noregr785_08_17_prueba_herencia2.ck2.zip)

**Comment by Darokrithia** [comment]
Hmmm, there have been a few updates since I really ran the whole program.  There's a good chance something changed in the meantime.  All of us are in school, but I'll try to take a look this weekend

**Comment by OwenDurkin** [comment]
This should be fixed since #15.
